### ISSUE TITLE
choose unique identifyer for models

### ISSUE THREAD

**Issue by BradleyScrim** [MaSyMoS/masymos-seek-middleware#6]
# Overview
- json checked in issue #2

## SEEK json
- [example](https://fairdomhub.org/models/20.json)
- `data.id`
    - points to the model, ignoring the version (**model id**)
    - i.e. `24`
- `data.meta.uuid`
    - points to the model, ignoring the version (**model uuid**)
    - i.e. `67bb3ce0-caa7-0138-f7f7-0242ac120004`
- `data.links.self`
    - points to the model + version without domain dependency (**model relative link**)
    - i.e. `/models/24?version=3`
- `data.attributes.version`
    - provides the current version number (**model version**)
    - i.e. `3`
- `data.attributes.versions.#.url` (_# is version number_)
    - provides the model + version with domain dependency (**model absolute link**)
    - i.e. `https://sandbox2.fairdomhub.org/models/24.json?version=3`

## possible uses
- full absolute URL to model, i.e. `https://sandbox2.fairdomhub.org/models/24`
    - **implies**: masymos-database needs a reset on domain change
    - **benefits**:
        - no configuration of seek domain needed
        - no stored metadata needed on masymos side
        - human-readable unique identifier
- `data.id` OR `data.meta.uuid`
    - **requires**: MaSeMiWa must have the SEEK-domain configured
    - **implies**: MaSeMiWa could identify, if model version is newer by saving `data.attributes.version` in graph meta data
- `data.links.self`
    - **requires**: MaSeMiWa must have the SEEK-domain configured
    - **possible benefits**:
        - MaSeMiWa could only use the ID on masymos-side
        - is domain independent

# ToDo
- [x] decide what UID to use → **full URL**
- [x] documentation

**Comment by mscholzj** [comment]
test for @BradleyScrim

**Comment by BradleyScrim** [comment]
Decision: **use the full absolute URL** to model, i.e. `https://sandbox2.fairdomhub.org/models/24` (SO, BW)
